### ISSUE TITLE
Have API outputs use 'prettified' JSON

### ISSUE THREAD

**Issue by marumari** [mozilla/tls-observatory#100]
Right now, the results API outputs very condensed JSON.  That's fine if it's only consumed by programs, but it makes it very hard to read as a human.

Pretty JSON doesn't use up that much more bandwidth, and it's far more legible and easy to work with, and it makes the API at least a little bit self-documenting.

**Comment by marumari** [comment]
BTW, if you are concerned about bandwidth, you can choose to only prettify it when you don't receive the X-Requested-With: XMLHttpRequest header.

**Comment by jvehent** [comment]
Bandwidth is indeed a concern because we're returning a lot of json responses, so paying for sending spaces seems suboptimal. I'm also dubious this adds any significant value when you have [json addons](https://addons.mozilla.org/en-US/firefox/addon/json-handle/?src=ss) for the browser, and `curl <url> | python -mjson.tool` for the command line.
