### ISSUE TITLE
Analysis section of API should be map instead of array

### ISSUE THREAD

**Issue by marumari** [mozilla/tls-observatory#127]
For analysis, instead of being an array like so:

```
analysis: [
    { analyzer: "mozillaGradingWorker", result: {}},
    { analyzer: "mozillaEvaluationWorker", result: {}}
]
```

It should be a map:

```
analysis: {
  mozillaGradingWorker: { result: {} }
  mozillaEvaluationWorker: { result: {} }
}
```

The way that it is currently designed is difficult to navigate; you have to iterate through analysis until you find the one you are looking for.  If it was a map, you could just look at api_result.analysis.mozillaGradingWorker, instead of having to search through the array to find it.

Not a big deal now, when there are just two and they are always in the same order.  But as it is now, mozillaGradingWorker went in front of mozillaEvaluationWorker, which broke code looking at the first item in the analysis array.

If it is changed to a map, you can add as many analyzers as you want, and you won't have to worry about it breaking any of the existing codebase.

**Comment by marumari** [comment]
Actually, upon looking at it, it seems that the analysis array *is* non-deterministic, meaning you do have to loop through it to find the analyzer you want.

**Comment by marumari** [comment]
(note that I've worked around this in my code, so it's not super high important, but I do think that this is the proper data structure)

**Comment by jvehent** [comment]
The current format is flexible: parser can go through the report without knowing which analyzers are present. Yes, you have to loop through the list, but it's a small price to pay to avoid updating data structure when we add or remove analyzers.

**Comment by marumari** [comment]
I forget that go makes it super hard to do all this stuff with its enforced data structures.  :\

**Comment by jvehent** [comment]
It's called static typing :smiling_imp: 
You don't have to use it, still I like the architecture better this way.

**Comment by marumari** [comment]
Pffle!  Anyways, you probably want to either:

a) Return them in a consistent order
b) Update the tlsobs client to return their values in a consistent order

Right now the command line tool returns the results in a random order, which is kind of weird.  :)

**Comment by jvehent** [comment]
Fair critism. Randomizing the output is not a good user experience (although a rather entertaining one). We should sort the order by which they appear.

**Comment by 0xdiba** [comment]
In the way the workers currently work it would be difficult to guarantee
their order, since they work concurrently and we receive the results
when each one finishes.

The whole purpose of this design for the workers is to be able to add them
transparently. I think that hardcoding their order, so basically having to
know
which workers will run beforehand, beats that purpose.

Putting them in a map is hardly any work for us and I doubt it changes
anything in our design or format ( since a map can be iterated without
knowing anything about its contents ),
but since it is randomized by default in Go it won't make much difference
on the presentation side ( it will only make it deterministic as April
mentioned ).

As a quick and dirty solution I think we could have the ordering as a
constant in each worker and sort by that on the presentation side ( be it
tlsobs client or the Website ).
Other than that we could run the workers synchronously one after the other
and make their order predictable,
but lose "speed" ( ok talking about speed for 2 workers might sound like a
joke but you get the point ;) ) .

**Comment by jvehent** [comment]
The internal execution of workers and the presentation of data are two completely isolated problems. I don't think we should care how data is inserted into the analysis array. We should simply sort it by worker name when presenting it to end users.

**Comment by 0xdiba** [comment]
I'm totally in favor of leaving the sorting to the presentation side ( and sorting by worker name is nice option ). Are we going for the result map or staying with the array and this issue is only about the tlsobs client?

**Comment by jvehent** [comment]
This is a backward incompatible change for a tool that is used by people over the internet. If we make that change, we need to move to `/api/v2` and maintain the same format for `/api/v1`.

April: do you think the current format is bad enough to warrant that amount of work around changing it?

**Comment by marumari** [comment]
Well, I mean, it already broke my tool because I had hard-coded for analysis[0].  📦 

Anyways, I'm ordering it on the client side and it's not the end of the world.  When we do get around to make it /api/v2, I think we should sanitize it and make it a map.

**Comment by jvehent** [comment]
Btw, `jq` has no problem working with this format :wink: 
`jq -r -c '.analysis[] | select(.analyzer | contains("mozillaEvaluationWorker")) | .result.level`
