### ISSUE TITLE
Include code points in API results

### ISSUE THREAD

**Issue by marumari** [mozilla/tls-observatory#138]
In the API, it could be great if:

`connection_info -> ciphersuite[n]`

Included the code points (particularly the IANA code point).  This is something that SSL Labs does on their results page, and it helps make comparison a lot easier across crypto libraries.  Thanks!

**Comment by tomato42** [comment]
that's definitely needed given that there are 3 incompatible sets of ChaCha20 ciphers

it will require changes to cipherscan though

**Comment by jvehent** [comment]
`openssl s_client` doesn't return the code point, so we'll need a [correspondance table](https://github.com/marumari/tls-table) to map the openssl ciphersuite to the code point.

I'm not sure if cipherscan cares about the code-point information. The CHACHA variants are already named `-OLD` in openssl. Maybe we should enrich the JSON in the observatory? But I'm happy to be convinced that cipherscan is a better spot for it.

**Comment by tomato42** [comment]
> openssl s_client doesn't return the code point, so we'll need a correspondance table to map the openssl ciphersuite to the code point.

or ask the openssl about the ID using `openssl ciphers -V`. But correspondance table is not bad, and I think testing is `cipher_id in set(ECDHE_kex_ciphers)` cleaner than the current grepping...

we could always embed the table in the joson output to make it easier for external stuff

also the problem is that there is name collision between SSLv2 and SSLv3 ciphers: `DES-CBC3-MD5` and `RC4-MD5` having them as IDs would be unambigous

> The CHACHA variants are already named `-OLD` in openssl. 

that's the case only for the openssl that's bundled, current 1.1.0 doesn't do that, it implements only the RFC ciphers

I want to extend cscan to test the full cipher space, and if server responds with any unknown ciphers we won't be able to do anything better than just note their IDs.

also, it will make the json files smaller :)

**Comment by 0xdiba** [comment]
We already generate a json of all the ciphers supported by openssl ( [here](https://github.com/mozilla/tls-observatory/blob/master/worker/mozillaGradingWorker/ciphersuites.go) ).
It would be trivial to include the code points in the json and just add extract them from there.

**Comment by jvehent** [comment]
I added code point support to the ciphersuite extractor in https://github.com/mozilla/tls-observatory/pull/182/commits/0b4ea1efd796ceb12dfc778f02c395d3537d1c07
Next step would be to use that data to enrich cipherscan's output in the scanner.
