### ISSUE TITLE
Cloudflare sites all return as "Insecure"

### ISSUE THREAD

**Issue by marumari** [mozilla/tls-observatory#186]
`threatresponse.cloud` is a site that has this issue, I think it's because of having the cipher ECDHE-ECDSA-CHACHA20-POLY1305-OLD, but I'm not entirely positive.

**Comment by marumari** [comment]
Also I believe it supports both CHACHA20-OLD and CHACHA20, but the TLS Observatory only shows the former.

**Comment by jvehent** [comment]
We'll need to add `ECDHE-ECDSA-CHACHA20-POLY1305-OLD` to the JSON recommendations to fix that. Support for scanning CHACHA20 is being discussed here: https://github.com/mozilla/cipherscan/issues/118

**Comment by grittygrease** [comment]
Can the policy be updated to just ignore support for ECDHE-ECDSA-CHACHA20-POLY1305-OLD in the rating determination? It's widely assumed that there are no significant security differences between this cipher and the RFC version. We support both. A large percentage of ChaCha20-enabled clients use this cipher (mostly older Chrome versions), so we are not inclined to disable support for it without a strong reason.

This issue is currently affecting millions of sites who are running on Cloudflare using our configuration, which we consider to be among the most secure configurations possible with broad compatibility.

**Comment by marumari** [comment]
So the trick here is that to make it part of "Modern", we would need to make it part of our Modern configurations:

https://wiki.mozilla.org/Security/Server_Side_TLS
https://github.com/mozilla/server-side-tls/blob/gh-pages/json/server-side-tls-conf.json

And I don't know if we want to recommend that people put the old code point in their server configurations.  Could we make a one-off exception in cipherscan/tls-observatory to treat it as the same as ChaCha20, instead of modifying the upstream recommendations?

**Comment by jvehent** [comment]
Blocked on https://github.com/mozilla/server-side-tls/issues/178
I'll try to get to it next week.

**Comment by jvehent** [comment]
I put a wart in the code to deal with this: https://github.com/mozilla/tls-observatory/commit/390a0500e0c3107845d08fe2747a702b1a461044
Now the config returns "non compliant" because it is somewhere in between modern and intermediate.

To get to modern, it would need:
  - for modern level: remove ciphersuites ECDHE-ECDSA-AES128-SHA, ECDHE-ECDSA-AES256-SHA, ECDHE-ECDSA-DES-CBC3-SHA
  - for modern level: consider adding ciphers ECDHE-RSA-AES256-GCM-SHA384, ECDHE-ECDSA-CHACHA20-POLY1305, ECDHE-RSA-CHACHA20-POLY1305, ECDHE-RSA-AES128-GCM-SHA256, ECDHE-RSA-AES256-SHA384, ECDHE-RSA-AES128-SHA256
  - for modern level: remove protocols TLSv1, TLSv1.1
  - for modern level: consider enabling OCSP stapling

And to get to intermediate:
  - for intermediate level: ecdsa-with-SHA256 is not an intermediate certificate signature, use sha256WithRSAEncryption
  - for intermediate level: consider adding ciphers ECDHE-ECDSA-CHACHA20-POLY1305, ECDHE-RSA-CHACHA20-POLY1305, ECDHE-RSA-AES128-GCM-SHA256, ECDHE-RSA-AES256-GCM-SHA384, DHE-RSA-AES128-GCM-SHA256, DHE-RSA-AES256-GCM-SHA384, ECDHE-RSA-AES128-SHA256, ECDHE-RSA-AES256-SHA384, ECDHE-RSA-AES128-SHA, ECDHE-RSA-AES256-SHA, DHE-RSA-AES128-SHA256, DHE-RSA-AES128-SHA, DHE-RSA-AES256-SHA256, DHE-RSA-AES256-SHA, ECDHE-RSA-DES-CBC3-SHA, EDH-RSA-DES-CBC3-SHA, AES128-GCM-SHA256, AES256-GCM-SHA384, AES128-SHA256, AES256-SHA256, AES128-SHA, AES256-SHA, DES-CBC3-SHA
  - for intermediate level: consider enabling OCSP stapling
  - for intermediate level: use a certificate of type rsa, not ECDSA

The next version of the guidelines will recommend ecdsa at the intermediate level, so all cloudflare sites should automatically be treated as such.

**Comment by jrchamp** [comment]
Thank you for not including the non-standard cipher in the modern list. After all, it was modified to address an issue, possibly a security issue.
