### ISSUE TITLE
Docker $gopath binaries

### ISSUE THREAD

**Issue by jammasterj89** [mozilla/tls-observatory#248]
I use the Docker version of tls-obs, and recently it has stopped working (I always pull the latest before use).

I've started from scratch to narrow the problem down. So, on a fresh system if I run:

`docker pull mozilla/tls-observatory`

Then run:

`docker run -it mozilla/tls-observatory tlsobs accounts.firefox.com`

I get the error:

`docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"tlsobs\": executable file not found in $PATH".`

This is because the `/go/bin` is empty.

I can fix this problem by running the makefile to build the binaries, but I previously didn't have to do this when running the docker container?

Thanks for the help!

**Comment by autrilla** [comment]
The binaries are now all moved under `/app`. I've opened #250 to make them be in `/go/bin` as well.

**Comment by jammasterj89** [comment]
Hi @autrilla, thanks for the quick reply.

Can I ask, there is no "tlsobs" binary under /app before or after running make, this binary only appears in /go/bin after running a "make"?

**Comment by autrilla** [comment]
Because of our internal conventions for containers, we put all binaries we use in production containers inside `/app`. We don't use the `tlsobs` binary on servers in production, so we don't put it there. I'd be okay with copying the `tlsobs` binary from `/go/bin` to `/app` like we do with the rest too. You should be able to keep using all binaries from `/go/bin` like you did in the past, no need to use the ones under `/app`.

**Comment by jammasterj89** [comment]
No problem, thank you for explaining :)

**Comment by autrilla** [comment]
I'm guessing this can be closed. Feel free to reopen if there's any other problem.
