### ISSUE TITLE
limit number of concurrent connections

### ISSUE THREAD

**Issue by jvehent** [mozilla/tls-observatory#57]
AWS applies a limit to the number of concurrent connections a given RDS database can accept. On the t2.medium we use for testing, that appears to be set to 120. We should limit how many connections the api and scanner are allowed to open using `SetMaxOpenConns()`, maybe by reusing the already present concurrency limit.

**Comment by 0xDiBa** [comment]
I don't know if <code>SetMaxOpenConns()</code> can help us much , because the api and the scanner are two different binaries so the only thing you can do is just guess and probably set something like ~60% of the open conns to the scanner and ~40% to the api.

More importantly in the scanner, if we pass those limits we might get errors for acknowledged scans.
Maybe a solution that uses <code>[DBStats](https://golang.org/pkg/database/sql/#DB.Stats)</code> to get the number of open connections to the database and start/postpone the scan depending on whether we are approaching the limit or not.

**Comment by jvehent** [comment]
Why do you think we would get errors for acknowledged scans? I think if we pass the limit, the scanner will fail to run `SELECT FOR  UPDATE` and thus not acknowledge the scan, so another scanner will pick it up. No?
